import os

from dotenv import load_dotenv
from openai import OpenAI

# PDF generation
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak
)

from reportlab.lib import styles
from reportlab.lib import colors

# prompts
from prompts.docs_prompt import (
    build_document_prompt
)

# vector retrieval
from utils.vector_memory import (
    vector_store
)

# repo memory
from utils.repository_memory import (
    repository_state
)

# load environment variables
load_dotenv()

# initialize Groq client
client = OpenAI(
    api_key=os.getenv(
        "GROQ_API_KEY"
    ),
    base_url=(
        "https://api.groq.com/openai/v1"
    )
)


def create_repo_folder():
    """
    Create repository-specific
    docs folder.

    Example:
    generated_docs/B09/
    """

    repo_name = (
        repository_state[
            "repo_name"
        ]
    )

    folder_path = os.path.join(
        "generated_docs",
        repo_name
    )

    os.makedirs(
        folder_path,
        exist_ok=True
    )

    return folder_path


def retrieve_context(
    query,
    top_k=15
):
    """
    Retrieve semantic context
    for document generation.
    """

    return vector_store.search(
        query=query,
        top_k=top_k
    )


def call_llm(
    prompt
):
    """
    Call Groq model.
    """

    response = (
        client.chat.completions.create(
            model=(
                "llama-3.3-70b-versatile"
            ),
            messages=[
                {
                    "role":
                        "system",

                    "content":
                        (
                            "You are a senior "
                            "technical "
                            "documentation "
                            "engineer."
                        )
                },
                {
                    "role":
                        "user",

                    "content":
                        prompt
                }
            ]
        )
    )

    return (
        response
        .choices[0]
        .message.content
    )


def save_markdown(
    folder_path,
    filename,
    content
):
    """
    Save markdown file.
    """

    file_path = os.path.join(
        folder_path,
        filename
    )

    with open(
        file_path,
        "w",
        encoding="utf-8"
    ) as file:

        file.write(content)

    print(
        f"Saved: {filename}"
    )


def save_srs_pdf(
    folder_path,
    content
):
    """
    Convert SRS markdown
    into professional PDF.
    """

    pdf_path = os.path.join(
        folder_path,
        "SRS.pdf"
    )

    document = (
        SimpleDocTemplate(
            pdf_path
        )
    )

    style_sheet = (
        styles.getSampleStyleSheet()
    )

    story = []

    # title
    story.append(
        Paragraph(
            "Software Requirements Specification",
            style_sheet[
                "Title"
            ]
        )
    )

    story.append(
        Spacer(1, 20)
    )

    story.append(
        Paragraph(
            (
                "Generated by "
                "CodeAtlas"
            ),
            style_sheet[
                "Italic"
            ]
        )
    )

    story.append(
        PageBreak()
    )

    # split markdown
    lines = (
        content.split("\n")
    )

    for line in lines:

        line = line.strip()

        if not line:
            continue

        # headings
        if line.startswith("#"):

            clean_text = (
                line.replace(
                    "#",
                    ""
                ).strip()
            )

            story.append(
                Paragraph(
                    clean_text,
                    style_sheet[
                        "Heading2"
                    ]
                )
            )

        else:

            story.append(
                Paragraph(
                    line,
                    style_sheet[
                        "BodyText"
                    ]
                )
            )

        story.append(
            Spacer(1, 8)
        )

    document.build(
        story
    )

    print(
        "Saved: SRS.pdf"
    )


def generate_single_doc(
    doc_type,
    filename,
    retrieval_query,
    folder_path
):
    """
    Generate one document.

    Flow:
    ----------
    retrieve context
        ↓
    build prompt
        ↓
    call LLM
        ↓
    save markdown
    """

    retrieved_chunks = (
        retrieve_context(
            retrieval_query
        )
    )

    prompt = (
        build_document_prompt(
            doc_type=
                doc_type,

            repo_analysis=
                repository_state[
                    "analysis"
                ],

            retrieved_chunks=
                retrieved_chunks,

            commits=
                repository_state[
                    "commits"
                ]
        )
    )

    print(
        f"\nGenerating "
        f"{filename}..."
    )

    content = (
        call_llm(
            prompt
        )
    )

    # special handling
    # for SRS PDF
    if doc_type == "srs":

        save_srs_pdf(
            folder_path,
            content
        )

    else:

        save_markdown(
            folder_path,
            filename,
            content
        )


def generate_docs():
    """
    Generate all docs.

    Main pipeline.
    """

    folder_path = (
        create_repo_folder()
    )

    documents = [

        {
            "type":
                "readme",

            "filename":
                "README.md",

            "query":
                (
                    "project overview "
                    "features tech stack "
                    "architecture"
                )
        },

        {
            "type":
                "architecture",

            "filename":
                "architecture.md",

            "query":
                (
                    "routes services "
                    "controllers database "
                    "architecture"
                )
        },

        {
            "type":
                "onboarding",

            "filename":
                "onboarding.md",

            "query":
                (
                    "setup structure "
                    "important files "
                    "entry points"
                )
        },

        {
            "type":
                "api_docs",

            "filename":
                (
                    "API_DOCUMENTATION.md"
                ),

            "query":
                (
                    "routes api "
                    "authentication "
                    "endpoints"
                )
        },

        {
            "type":
                "risk_analysis",

            "filename":
                (
                    "RISK_ANALYSIS.md"
                ),

            "query":
                (
                    "architecture "
                    "database auth "
                    "middleware"
                )
        },

        {
            "type":
                "srs",

            "filename":
                "SRS.pdf",

            "query":
                (
                    "features workflows "
                    "architecture "
                    "requirements"
                )
        }
    ]

    # generate all docs
    for document in documents:

        generate_single_doc(
            doc_type=
                document["type"],

            filename=
                document[
                    "filename"
                ],

            retrieval_query=
                document[
                    "query"
                ],

            folder_path=
                folder_path
        )

    return {
        "success": True,

        "message":
            (
                "Documentation "
                "generated"
            ),

        "folder":
            folder_path
    }